### PR TITLE
Boilerplate code

### PR DESCRIPTION
**Pull request by stevesoltys**
These commits contain the boilerplate code for the torrent library. Let me know if there is anything structurally that you would like to change @garyttierney.

### CODE REVIEW

**Comment by garyttierney** [comment]
Had a quick glance over it on the way to work. Looks OK, will check out SRC earlier and hack around.
On 26 Oct 2015 4:17 am, Steve Soltys <notifications@github.com> wrote:Assigned #1 to @garyttierney.

**Comment by garyttierney** [comment]
@stevesoltys bit of scope is required for this.

I'd prefer if we specced this out via flow diagrams or something. It's a little unclear to view on first glance.

What is the purpose of `TorrentFileManager` - is the purpose of this library manage torrents or is it simply a library to read / create a Torrent and start downloading / uploading it?

I think it's better to get connectivity going first before starting to do any of this.

Closing for now.

**Comment by stevesoltys** [comment]
In the BitTorrent protocol, the data for a particular torrent is read as a stream of bytes. Since any point in a particular chunk can be the end of a file, partitioning of that chunk will be required in order to write the correct data to the correct file.

The purpose of ``TorrentFileManager`` is to do exactly that. It will be responsible for managing the file structure of a torrent.

As a side note, I will be pushing commits either tonight or tomorrow for ``TrackerSession``, which will perform a handshake with a tracker and maintain a session.

**Comment by garyttierney** [comment]
@stevesoltys oh okay, bit of a weird name for a wrapper around random access though

**Pull request closed without merging**
